### ISSUE TITLE
I am confused by the results I have reproduced, I cannot achieve the effects in your paper? No parameters had been modified, just by default

### ISSUE THREAD

**Issue by YooLiuXiao** [jiajunsi/RCML#2]

**Comment by jiajunsi** [comment]
We have thoroughly retested our experimental results, and we are pleased to report that the outcome of the experiment remains unaffected by any issues. If you have any inquiries or concerns, please compile them and kindly forward them to my email address at jiajunsi@stu.xidian.edu.cn. Rest assured, we are committed to assisting you in resolving any questions you may have. 
Thank you for your attention!
