### ISSUE TITLE
Question about HMDB and Caltech101 Dataset Feature Extraction

### ISSUE THREAD

**Issue by stillwater-cheng** [jiajunsi/RCML#7]
Hello,

I hope this message finds you well.

I have a question regarding the HMDB and Caltech101 datasets. Do I need to handle the view extraction myself, or are there publicly available resources for this? If possible, could you please provide a link?

Thank you very much for your assistance!

**Comment by YilinZhang107** [comment]
Sorry for the late reply to your question.

You can certainly process the raw dataset as described in the paper to get different views. Here are the links to access the two original datasets:
* HMDB: https://serre-lab.clps.brown.edu/resource/hmdb-a-large-human-motion-database/ 
* Caltech101: https://data.caltech.edu/records/mzrjq-6wc02.

We also provide the processed datasets, which can be accessed from within the link provided by this repository: 
* https://github.com/YilinZhang107/Multi-view-Datasets.

Thank you again for your interest.
